name: contact_with_object_box
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^2.4.0
  objectbox_flutter_libs: ^2.4.0
  riverpod: ^2.5.0
  riverpod_annotation: ^2.3.4
  path: ^1.8.3
  path_provider: ^2.1.2
  flutter_riverpod: ^2.4.10
  shared_preferences: ^2.2.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  
  objectbox_generator: ^2.4.0
  riverpod_generator: ^2.3.10
  

flutter:
  uses-material-design: true
